# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:16
from __future__ import unicode_literals

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='apartments',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apartments'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city_village',
            field=models.CharField(default='Kiev', max_length=100, verbose_name='City or village'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Ukraine', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
